# Generated by Django 3.0.6 on 2020-05-19 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_content', models.TextField()),
                ('mutation_type', models.IntegerField(choices=[(0, 'Rephrase'), (1, 'Negate'), (2, 'Similar'), (3, 'Dissimilar'), (4, 'More specific'), (5, 'More general')],
                                                      blank=True, null=True)),
                ('by_supervisor', models.BooleanField(default=False)),
                ('annotated_count', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='wiki.Page')),
                ('parent_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wf1.Claim', null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='wiki.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
