# Generated by Django 3.0.6 on 2020-05-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wf1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(0, 'Supported'), (1, 'Refuted'), (2, 'Not enough information')])),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('claim', models.ManyToManyField(related_name='labels', to='wf1.Claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
