# Generated by Django 3.0.8 on 2020-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='label_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
