# Generated by Django 3.0.6 on 2020-05-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('page_content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Not used'), (1, 'Chosen'), (2, 'Claim generated')], default=0)),
                ('useless', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_content', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='wiki.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('first_paragraph', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('pages', models.ManyToManyField(related_name='hyperlinks', to='wiki.Page')),
                ('sentences', models.ManyToManyField(related_name='hyperlinks', to='wiki.Sentence')),
            ],
        ),
    ]
