# Generated by Django 3.0.6 on 2020-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='checked_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
